//data.js
export const productos = [
    {
      id: 1,
      nombre: "ALEJANDRA Y SOFIA",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/public/img/1.png",
      modelo: "/public/model/1.glb",
      marcadorAR: false,
    },
    {
      id: 2,
      nombre: "ANDRES Y LAURA",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/2.png",
      modelo: "/model/2.glb",
      marcadorAR: false,
    },
    {
      id: 3,
      nombre: "ESTEFANIA Y MARIANA",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/3.png",
      modelo: "/model/3.glb",
      marcadorAR: false,
    },
    {
      id: 4,
      nombre: "JUAN DIEGO GONZALES",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/4.png",
      modelo: "/model/4.glb",
      marcadorAR: false,
    },
    {
      id: 5,
      nombre: "LAURA BALANTA Y ISABELLA MAMIAN",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/5.png",
      modelo: "/model/5.glb",
      marcadorAR: false,
    },
    {
      id: 6,
      nombre: "LAURA MARROQUI Y ISABELLA",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/6.png",
      modelo: "/model/6.glb",
      marcadorAR: false,
    },
    {
      id: 7,
      nombre: "LAURA MAYELA Y ELIZABETH",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/7.png",
      modelo: "/model/7.glb",
      marcadorAR: false,
    },
    {
      id: 8,
      nombre: "MAURY Y MARIA DEL MAR",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/8.png",
      modelo: "/model/8.glb",
      marcadorAR: false,
    },
    {
      id: 9,
      nombre: "NATALIA Y NICOLLE",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/9.png",
      modelo: "/model/9.glb",
      marcadorAR: false,
    },
    {
      id: 10,
      nombre: "NATHALY Y DAYANA",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/10.png",
      modelo: "/model/10.glb",
      marcadorAR: false,
    },
    {
      id: 11,
      nombre: "SARAY Y SHARON",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/11.png",
      modelo: "/model/11.glb",
      marcadorAR: false,
    },
    {
      id: 12,
      nombre: "SOFIA PAMPLONA",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/12.png",
      modelo: "/model/12.glb",
      marcadorAR: false,
    },
    {
      id: 13,
      nombre: "SOFIA Y DIEGO",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/13.png",
      modelo: "/model/13.glb",
      marcadorAR: false,
    },
    {
      id: 14,
      nombre: "YESSICA VALENCILLA",
      Diseno: "Nombre del Diseño",
      informacion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mollis id quam nec pretium. Integer auctor eros pulvinar mattis fringilla. Nulla vel sagittis dui. Ut sagittis nisl sed lectus auctor tempus. Nulla a luctus leo. Fusce id venenatis nibh. Phasellus vulputate ligula pellentesque dignissim tincidunt. Donec ac purus justo. Sed cursus imperdiet gravida. Proin risus erat, accumsan nec elementum at, vulputate vel lorem. Nulla nec lectus sit amet urna eleifend fringilla. Aenean sed justo magna. Ut et massa tincidunt, iaculis elit eget, tristique purus. Pellentesque ac varius ligula. Vivamus augue ante, gravida quis tincidunt et, porta nec nunc. Integer dui eros, pulvinar eget pharetra eget, elementum vel leo.",
      imagen: "/img/14.png",
      modelo: "/model/14.glb",
      marcadorAR: false,
    },
  ];
  