//data.js
export const productos = [
    {
      id: 1,
      nombre: "ALEJANDRA Y SOFIA",
      Diseno: "FUEGO EN MOVIMIENTO",
      informacion: "",
      imagen: "/img/1.png",
      modelo: "/model/ALEJAYSOFI.glb",
      marcadorAR: false,
    },
    {
      id: 2,
      nombre: "ANDRES Y LAURA",
      Diseno: "COOLFLEX",
      informacion: "",
      imagen: "/img/2.png",
      modelo: "/model/Andres&Laura.glb",
      marcadorAR: false,
    },
    {
      id: 3,
      nombre: "ESTEFANIA Y MARIANA",
      Diseno: "ETER EN MOVIMIENTO",
      informacion: "Este vestuario, inspirado en Dernière Danse de Indila, trasciende la gimnasia artística para convertirse en una pieza de expresión emocional. Con influencias del neo-roman-ticismo gótico y la vanguardia, refleja la dualidad entre la fragilidad y la fuerza de un alma en tránsito entre el pasado y la liberación. Pensado como una extensión del cuerpo, el diseño responde a cada movimiento, narrando a través de bordados y aplicaciones una historia de resiliencia. Grietas doradas evocan el kintsugi japonés, abstracciones sugieren un vuelo interrumpido y las transparencias juegan con la tensión entre lo visible y lo oculto. La paleta de colores —azul noche, burdeos y negro profundo, con acentos metálicos y nacarados— representa la belleza melancólica del atardecer, dotando al vestuario de un dramatismo visual que potencia la expresión corporal.", 
      imagen: "/img/3.png",
      modelo: "/model/estefania y mariana.glb",
      marcadorAR: false,
    },
    {
      id: 4,
      nombre: "JUAN DIEGO GONZALES",
      Diseno: "ECOS SALSEROS",
      informacion: "",
      imagen: "/img/4.png",
      modelo: "/model/4.glb",
      marcadorAR: false,
    },
    {
      id: 5,
      nombre: "LAURA BALANTA E ISABELLA MAMIAN",
      Diseno: "OVERDRIVE",
      informacion: "Overdrive ha sido desarrollado con un enfoque integral que combina protección, funcionalidad, visibilidad y estilo. Este traje de BMX se Compone de materiales como Bahía, Optico Plus y Segal Wickings, seleccionados por sus propiedades técnicas que permiten al ciclista moverse con libertad, mantenerse cómodo y enfrentar condiciones exigentes propias del BMX. Bahía ofrece elasticidad y un ajuste cenido que favorece la aerodinámica; Optico Plus aporta durabilidad y nitidez en los gráficos del tejido; mientras que Segal Wickings destaca por su resistencia a impactos y a la fricción, siendo un material robusto que no se daña fácilmente ante caídas o roce constante con el terreno. La elección de los colores morado y azul vibrante responde a una intención clara de transmitir fuerza, individualidad y modernidad. El morado simboliza creatividad, energía y carácter. reflejando la personalidad audaz del ciclista. El azul vibrante aporta un efecto visual llamativo que evoca velocidad, precisión y confianza, al mismo tiempo que mejora la visibilidad del deportista en movimiento. Esta paleta de colores crea una identidad visual única y poderosa, alineada con el estilo competitivo y. expresivo del BMX. Como detalle final, Overdrive incorpora un sistema de aromatización textil con menta y lavanda. La menta proporciona una sensación de frescura constante, ayudando a combatir la fatiga durante el esfuerzo físico, mientras que la lavanda aporta un efecto relajante y calmante, ideal para reducir el estrés y mantener el enfoque antes y durante la competencia. Así, Overdrive representa una fusión entre diseño inteligente, tecnología textil avanzada y expresión personal, pensado para acompañar al deportista en cada salto, cada giro y cada caída, con seguridad, estilo y frescura.",
      imagen: "/img/5.png",
      modelo: "/model/ISABELLALAURABALANTA.glb",
      marcadorAR: false,
    },
    {
      id: 6,
      nombre: "LAURA MARROQUI E ISABELLA",
      Diseno: "EL RITMO HECHO PIEL",
      informacion: "El ritmo hecho piel, un traje inteligente inspirado en la pasión escénica de la salsa en línea estilo Los Angeles, donde cada destello de luz LED acompaña el ritmo preciso del cuerpo que vibra con la música. Confeccionado en telas que abrazan la silueta y liberan el movimiento, este vestuario no solo deslumbra en escena, sino que cuida con sutileza la zona lumbar del bailarín, incorporando discretas bolsas térmicas de gel que alivian el esfuerzo después de cada giro. Es un diseño que no solo viste el arte de bailar, sino que lo protege, lo acompaña y lo celebra, haciendo del cuerpo un territorio donde la tenología y el ritmo se encuentran con ternura y poder. Este vestuario escénico parte de una silueta tipo bodysuit en terciopelo verde, cuya textura profunda realza la figura y transmite elegancia. Los destellos de pedrería crean un juego sutil con la luz, mientras las plumas sintéticas en los laterales aportan volumen y movimiento, evocando la ligereza de un plumaje etéreo.",
      imagen: "/img/6.png",
      modelo: "/model/6.glb",
      marcadorAR: false,
    },
    {
      id: 7,
      nombre: "LAURA MAYELA Y ELIZABETH",
      Diseno: "CORE MOMENTUM",
      informacion: "Cuando el cuerpo se exige al máximo, la ropa debe estar a la altura. Core Momentum no es solo un uniforme: es una segunda piel diseñada para impulsar el rendimiento, proteger el bienestar y liberar el potencial de cada jugadora. Diseñado especialmente para el equipo femenino de voleibol de la Universidad San Buenaventura Cali, Core Momentum tiene el potencial de adaptarse a cualquier equipo deportivo que busque alto rendimiento, confort y funcionalidad. Su silueta ergonómica permite movimiento libre y seguro, gracias a textiles con elongación en cuatro vías, transpirabilidad y secado rápido. En el área del pecho, se integró un tejido que mejora el deslizamiento, reduciendo fricción en situaciones de contacto. Uno de sus mayores avances es la incorporación de microcápsulas de eucalipto con gel antibacterial, que se activan con el movimiento, liberando una mezcla que neutraliza olores, disminuye el estrés y la ansiedad, y aporta un efecto antibacteriano que mantiene la prenda fresca e higiénica. La propuesta de color combina funcionalidad y creatividad, reforzando la identidad del equipo y aportando una estética moderna y competitiva.Core Momentum es una prenda tecnológica, versátil y pensada para elevar la experiencia deportiva con innovación y propósito.",
      imagen: "/img/7.png",
      modelo: "/model/7.glb",
      marcadorAR: false,
    },
    {
      id: 8,
      nombre: "MAURY Y MARIA DEL MAR",
      Diseno: "RENACER",
      informacion: "",
      imagen: "/img/8.png",
      modelo: "/model/Maury&MariaDelMar.glb",
      marcadorAR: false,
    },
    {
      id: 9,
      nombre: "NATALIA Y NICOLLE",
      Diseno: "Rendimiento, Estilo y Salud: El Futuro de la Gimnasia aeròbica",
      informacion: "'Rendimiento, Estilo y Salud: El Futuro de la Gimnasia aeròbica' Este diseño está pensado especificamente para deportistas de gimnasia aeróbica, disciplina que exige tanto potencia física como una fuerte presencia escénica. La prenda, de silueta ajustada y confección anatómica, se adapta al cuerpo como una segunda piel, permitiendo una amplia libertad de movimiento sin perder su funcionalidad ni su carácter estético. El degradado en tonos cálidos con acentos metircos crea una superficie visual dinámica que acompaña el ritmo del cuerpo en acción, y al mismo tiempo, transmite fuerza, elegancia y determinación. Más allá de su funcionalidad, esta propuesta explora un lenguaje visual que representa la dualidad entre fuerza interior y sensibilidad. La estética minimalista, con recortes sutiles y líneas que abrazan la figura, expresa una vulnerabilidad honesta que convive con la disciplina y el control que exige el deporte. Cada elemento del diseño contribuye a narrar un momento de equilibrio: un punto de encuentro entre lo técnico y lo emocional, entre la potencia del cuerpo y la sutileza del alma. TALLER", 
      imagen: "/img/9.png",
      modelo: "/model/natynicol.glb",
      marcadorAR: false,
    },
    {
      id: 10,
      nombre: "NATHALY Y DAYANA",
      Diseno: "SOMMERSO",
      informacion: "",
      imagen: "/img/10.png",
      modelo: "/model/NATYDAYANA.glb",
      marcadorAR: false,
    },
    {
      id: 11,
      nombre: "SARAY Y SHARON",
      Diseno: "ZONA CERO",
      informacion: "Inspirado en la potencia, disciplina y conexión de los atletas universitarios, 'zona cero' simboliza la unión entre cuerpo, mente y equipo. El diseño re eja la identidad de una institución (USB), resaltando el orgullo por representar sus colores y su legado en cada jugada. La estética combina modernidad con dinamismo visual, haciendo honor a la fuerza interior del jugador.El uniforme 'zona cero' presenta una silueta atlética con cortes limpios que acentúan lamusculatura y movilidad del jugador. Predomina el negro como base, lo que transmite poder y concentración, mientras que los detalles en naranja intenso aportan energía, visibilidad y carácter competitivo. La tipografía del número del jugador y las siglas 'USB' destacan con rmeza en el pecho, reforzando el sentido de pertenencia. Las líneas gráficas asimétricas en el costado añaden movimiento visual, evocando velocidad y estrategia. El conjunto se complementa con mangas compresoras y una estética que resalta en el campo y fuera de el, ideal para todos los partidos y presentaciones del equipo.",
      imagen: "/img/11.png",
      modelo: "/model/sharon y saray .glb",
      marcadorAR: false,
    },
    {
      id: 12,
      nombre: "SOFIA PAMPLONA",
      Diseno: "FASHION CULTURE",
      informacion: "Fusion Culture es una obra visual que encapsula la energía, el ritmo y la diversidad cultural de la salsa, un género musical nacido del encuentro vibrante entre naciones y tradiciones. Este vestuario no solo adorna el cuerpo, sino que narra una historia de mestizaje y herencia. Diseñado con un corte asimétrico y dinámico que emula el movimiento constante del baile, el vestido fluye con gracia y pasión, como lo hacen los cuerpos al ritmo de los tambores, las trompetas y las claves. La falda en cascada, que cae más larga en un lateral, evoca la libertad del movimiento y la espontaneidad del estilo salsero. La pieza destaca por su sublimado en tonos neón de fucsia y naranja, colores que vibran con vida propia bajo las luces del escenario. Estos tonos no solo representan la calidez tropical de Cuba, la energía vibrante de Puerto Rico y la pasión urbana de Nueva York, sino que también rinden homenaje a todos los rincones del Caribe y América Latina que dieron forma al género. La tecnología neón aplicada en el sublimado no es solo estética: es una declaración de modernidad que conecta pasado y presente, tradición e innovación. Los detalles en malla color piel y resortes tono piel generan un efecto visual de piel descubierta que aporta sensualidad y elegancia, sin perder el enfoque atlético y artístico del vestuario. Estas transparencias sutiles representan la apertura y conexión entre culturas: no hay barreras, solo armonía y fusión.",
      imagen: "/img/12.png",
      modelo: "/model/Csofiapamaverotra.glb",
      marcadorAR: false,
    },
    {
      id: 13,
      nombre: "SOFIA Y DIEGO",
      Diseno: "FUEGO, RITMO Y FLUIDEZ",
      informacion: "Fuego, Ritmo y Fluidez es un vestuario diseñado para resaltar el cuerpo en movimiento a través de la fuerza simbólica del fuego. Los colores rojo, naranja, amarillo y blanco fueron seleccionados cuidadosamente por su significado: representan la pasión, la energía, la chispa del ritmo y la pureza de la luz en escena. El pareo, con forma de llama, fue creado con líneas dinámicas que siguen el contorno del diseño, aportando una estética vibrante que acompaña los giros y desplazamientos de la bailarina. El body, elaborado en Polilicra Jabón sublimada con diseño exclusivo, se adapta al cuerpo brindando soporte, realce y comodidad. Como aporte funcional, se aplicó una microencapsulación antibacterial con menta, elegida por sus propiedades refrescantes y su capacidad para neutralizar olores durante el performance. Este vestuario no solo propone una estética llamativa, sino que fusiona tecnología textil y funcionalidad, creando una experiencia visual y sensorial completa en la escena.", 
      imagen: "/img/13.png",
      modelo: "/model/SOFY Y DIEGO.glb",
      marcadorAR: false,
    },
    {
      id: 14,
      nombre: "YESSICA VALENCILLA",
      Diseno: "LATIDO SALSERO",
      informacion: "",
      imagen: "/img/14.png",
      modelo: "/model/yesica.glb",
      marcadorAR: false,
    },
  ];
  